### ISSUE TITLE
Additional light shadows not working 2020.2f1 and 2021.1.0b3

### ISSUE THREAD

**Issue by BeardDevelop** [Cyanilux/URP_ShaderGraphCustomLighting#1]
I pulled this repository into a fresh unity 2020.21f1 project and found that the realtime additional light shadows are not working for the example toon shader with spotlights. I tried the same for 2021.1.0b3 with spotlights and pointlights. 
furthermore I tried:
- enabling the keyword via script as outlined in your article
- setting the boolean in the graph to true
- checked if shadows are enabled in the RP asset

I am not sure what I am missing at this point, but please let me know if I overlooked or misunderstood anything

**Comment by Cyanilux** [comment]
If you're using URP v10+, it looks like the GetAdditionalLight function no longer calculates shadows unless a third "shadowMask" parameter is used (see [Lighting.hlsl](https://github.com/Unity-Technologies/Graphics/blob/a197e35ba4e93349ccbb4fddd4f3f80ba7b1c113/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl#L225)) (v10.2.2).

I think this could just be `half4(1,1,1,1)`. Though looking at Lit.shader / LitForwardPass.hlsl, the more "correct" way, seems to be :
`shadowMask = SAMPLE_SHADOWMASK(input.lightmapUV);`

**Comment by BeardDevelop** [comment]
Thanks for your quick response! I'll look into it later today. This repository has been the most helpful on the topic of custom lighting so far. It's nicely documented and very clear (unlike unity's own projects using custom lighting etc..). The only downside was that it was not easy to find, you could consider doing a video on it or post something on the unity subreddit.

**Comment by BeardDevelop** [comment]
I can confirm that `half4(1,1,1,1)` works. It too works for point lights in V11.0.0

**Comment by Cyanilux** [comment]
Great, maybe I'll look into updating the functions at some point and look into the shadowmask stuff more in order to correctly support it. (Will also use the version define checks to prevent breaking it for pre-v10.1 versions of course)

I know it's related to a specific type of baked lighting but that's mostly all I know about it. `half4(1,1,1,1)` is apparently what it uses if Unity isn't set to bake shadowmasks but I'd assume it wouldn't look right if the user wanted to include baked shadows. Hoping it's just the SAMPLE_SHADOWMASK like I mentioned above but need to find some time to actually test it out.

The main light shadows one likely also needs updating too. Until I get around to making those changes, probably good to leave the issue open as a reminder and in case others have the same issue.
