### ISSUE TITLE
is additional light shadow node possible？

### ISSUE THREAD

**Issue by 21-brother** [Cyanilux/URP_ShaderGraphCustomLighting#16]
i want to adjust the shadows from both mainlight and additional light.

**Comment by Cyanilux** [comment]
Probably need to write your own version of the AdditionalLights function, as the adjustments to the shadows may need to be handled inside the loop

**Comment by demolen** [comment]
I'm also seeking the same. e.g. getting ShadowAtten for all the lights, not only the main directional light. Would you please give me some hints where to modify and look for in the AdditionalLights funtion for this? It would also be good if you could add an example for a lit base lit shader in shader graph (with an unlit master node) so I we (as noobs) can understand the usage of your nodes better.

**Comment by Cyanilux** [comment]
> getting ShadowAtten for all the lights, not only the main directional light. Would you please give me some hints where to modify and look for in the AdditionalLights funtion for this?

I think _it depends_ on what you're trying to achieve.
Additional lights are usually additively combined as they can overlap - one part in shadow could be lit up by another light. I'm not sure it really makes sense to combine only the ShadowAtten. They should still have falloff (DistanceAtten) and colours.
Perhaps you want a function similar to AdditionalLights_float but without the LightingLambert/LightingSpecular, and just a single output that adds all the attenuated colours (`Result += attenuatedLightColor;`?)

> It would also be good if you could add an example for a lit base lit shader in shader graph (with an unlit master node) so I we (as noobs) can understand the usage of your nodes better.

Might look into it, but for now the Toon graph should provide an example of this. That should basically be the same as the URP/SimpleLit iirc, just using a ramp texture to provide different falloff for lights. (and AdditionaLightsToon_float rather than AdditionalLights_float, but you could swap that out)
